### ISSUE TITLE
dbReadTable does not pass arguments on

### ISSUE THREAD

**Issue by hannesmuehleisen** [r-dbi/DBI#248] opened 2018-06-21 11:30 UTC
dbReadTable takes ... arguments but does not pass those on to dbSendQuery. Is this intentional?

**Comment by krlmlr** [comment] 2018-08-26 15:09
Thanks. Current `dbReadTable()` passes the dots only to `dbQuoteIdentifier()`, not to `dbGetQuery()` . They aren't used in `dbQuoteIdentifier()`, but why would we want them in `dbGetQuery()` ?

It seems interesting to explicitly support the `n` argument, though.

**Comment by krlmlr** [comment] 2018-08-27 00:00
Closing as duplicate of #240.

**Closed by krlmlr** 2018-08-27 00:00 UTC
