### ISSUE TITLE
Add ability to limit the number of records returned by dbReadTable

### ISSUE THREAD

**Issue by ronblum** [r-dbi/DBI#275] opened 2019-02-07 16:01 UTC
It would be useful to specify the number of rows returned by `dbReadTable`. Something like
```
dbReadTable(con, "myTable", n = 10)
```

This would be the equivalent of 
```
SELECT * from myTable LIMIT 10
SELECT TOP 10 * from myTable
```
etc., depending on the database's syntax.

**Comment by krlmlr** [comment] 2019-02-08 09:10
Duplicate of #240.

**Closed by krlmlr** 2019-02-08 09:10 UTC
