### ISSUE TITLE
Error: Cannot pass NA to dbQuoteIdentifier() dbname is datablock-db

### ISSUE THREAD

**Issue by danyal123** [r-dbi/DBI#219] opened 2018-01-24 19:48 UTC
I am trying to load a table from a csv using monetdb.read.csv I have narrowed down the problem to the data base name the db i am trying to creat the table name is called datablock-db if i change the database name to test or anything that does not have a "-" in it the following code works has anyone come across a similar problem

monetdb.read.csv(monetDBConn, "test_man.csv","test_gsub_3",delim=",",newline ="\\n")
Error: Cannot pass NA to dbQuoteIdentifier()

**Comment by krlmlr** [comment] 2018-01-25 12:37
Thanks. This isn't enough information to understand the cause of the problem. Could you please provide a reproducible example that I can run on my machine? The [reprex package](http://reprex.tidyverse.org) is very helpful.

**Comment by danyal123** [comment] 2018-01-25 19:40
library(MonetDB.R)
library(DBI)
library(plyr)

monetDB <- c()
monetDB$host <- "localhost"
monetDB$dbname <-"datablock-db"
monetDB$user <-"monetdb"
monetDB$password <-"monetdb"
monetDB$port <-"8080"

db <- dbConnect(MonetDB.R(), host=monetDB$host ,dbname=monetDB$dbname, user=monetDB$user, password=monetDB$password,port=monetDB$port)
nrow( mtcars )
dbWriteTable( db , 'mtcars1' , mtcars )
dbWriteTable( db , 'mtcars2' , mtcars )
dbWriteTable( db , 'mtcars3' , mtcars )

dbSendUpdate(db,"CREATE TABLE mtcars AS SELECT * FROM mtcars1 UNION ALL SELECT * FROM mtcars2 UNION ALL SELECT * FROM mtcars3 WITH DATA")

this code does not work as is, but i change the database name to something that does not have "-" in it then the code runs just fine

**Comment by krlmlr** [comment] 2018-01-25 19:43
Thanks. What's the error message, which command causes it?

**Comment by danyal123** [comment] 2018-01-25 19:49
Error: Cannot pass NA to dbQuoteIdentifier()
the following line is where the error occurs and to be specific its the db part the script fails to make a connection when there is a "-" in the database name

dbSendUpdate(db,"CREATE TABLE mtcars AS SELECT * FROM mtcars1 UNION ALL SELECT * FROM mtcars2 UNION ALL SELECT * FROM mtcars3 WITH DATA")

**Comment by hannesmuehleisen** [comment] 2018-01-25 19:50
Please try with MonetDBLite from CRAN, MonetDB.R has not been updated in ages.
`dbConnect(MonetDBLite::MonetDB.R()`

**Comment by danyal123** [comment] 2018-01-25 20:04
I tried that same error is persisting  and sitt no error when i change the database name

**Comment by hannesmuehleisen** [comment] 2018-01-25 20:09
I have just tried the example you provided on a database with a `-` in the name. Worked for me. Whats the output of `sessionInfo()` on your platform?

**Comment by danyal123** [comment] 2018-01-25 20:40
library(MonetDB.R)
library(DBI)
library(plyr)
library(MonetDBLite)

monetDB <- c()
monetDB$host <- "localhost"
monetDB$dbname <-"datablock-db"
monetDB$user <-"monetdb"
monetDB$password <-"monetdb"
monetDB$port <-"8080"

monetDBConn <- dbConnect(MonetDBLite::MonetDB.R(),host=monetDB$host ,dbname=monetDB$dbname, user=monetDB$user, password=monetDB$password,port=monetDB$port)
)
monetdb.read.csv(monetDBConn, "trend_all.csv","trend_all",delim=",",newline = "\\n")

**Comment by danyal123** [comment] 2018-01-25 20:40
session info output is 
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.2

**Comment by hannesmuehleisen** [comment] 2018-01-26 06:32
Please try updating your packages, I ran your script here and again it works fine. Which package versions do you have installed? (You can use `installed.packages()` to find out).

**Comment by krlmlr** [comment] 2018-04-30 22:07
Closing, please open a new issue if problems persist. (Please use the MonetDB.R issue tracker for problems with that backend.)

**Closed by krlmlr** 2018-04-30 22:07 UTC
