### ISSUE TITLE
`dbWriteTable` fails to find tables in non-default schemas

### ISSUE THREAD

**Issue by mmastand** [r-dbi/DBI#181] opened 2017-06-13 22:16 UTC
I am having trouble using `dbWriteTable` to output my dataframe to an MS SQL Server table.  I can do it when the schema is default but not if I try to use an alternate schema. See below:

```# Before running this example, create the table in SQL Server via
# CREATE TABLE [guest].[MikeTestTable](
# [a] [float] NULL,
# [b] [float] NULL,
# [c] [varchar](255) NULL)

# df to insert
df <- data.frame(a=c(10,20,30),
                 b=c(20,40,60),
                 c=c('oneT','twoT','threeT'))

# connection string
MSSQLConnectionString <- '
  driver={SQL Server};
  server=localhost;
  database=SAM;
  trustedConnection=true;
  '

# DBI connection
con <- DBI::dbConnect(odbc::odbc(),
                      .connection_string = MSSQLConnectionString)

# query to read from table
q <- "SELECT [a]
,[b]
,[c]
FROM HCRWriteData"

# get data
dfOut <- DBI::dbGetQuery(con, q)
head(dfOut)
     [1] a b c
     <0 rows> (or 0-length row.names)

# now try to write contents of df to the table.
# this table uses the default schema.
DBI::dbWriteTable(conn = con, 
                  name = 'HCRWriteData', 
                  value = df,
                  append = TRUE)

# get data after writing
dfOut <- DBI::dbGetQuery(con, q)
head(dfOut
      a  b      c
     1 10 20   oneT
     2 20 40   twoT
     3 30 60 threeT

### Using non-default schema
# query to read from table
q2 <- "SELECT [a]
,[b]
,[c]
FROM [SAM].[guest].[MikeTestTable]"

# get data
dfOut <- DBI::dbGetQuery(con, q2)
head(dfOut)
     [1] a b c
     <0 rows> (or 0-length row.names)

#Finally, writing to the non-default schema:
# this table uses a non-default schema
DBI::dbWriteTable(conn = con, 
                  name = 'guest.MikeTestTable', 
                  value = df,
                  append = TRUE)

# get data
dfOut <- DBI::dbGetQuery(con, q2)
head(dfOut)
     Error: Table guest.MikeTestTable does not exist
```

I can read from either table, but only write to a default schema.

**Comment by jcpayne** [comment] 2017-06-26 03:45
I use this syntax:
`dbWriteTable(con, c("schema","table"),dataframe)`
I haven't seen it documented anywhere but it works for me.

**Comment by EthanTaft** [comment] 2017-07-26 18:54
using `dbWriteTable(con, c("schema","table"), dataframe)` does not work.  It returns:
`Error: length(name) == 1 is not TRUE` because the table name is not of length one.

**Comment by jcpayne** [comment] 2017-07-26 19:24
Strange.  I just tried it and it worked for me:
dbWriteTable(con, c("public","test"), test)
[1] TRUE

Maybe it's a R or RStudio version issue?  I have RPostgreSQL loaded, which 'depends' on DBI.

**Comment by EthanTaft** [comment] 2017-07-26 19:37
I wonder. I'm using R 3.4.1

Your command runs, but with a caveat.  If I run `DBI::dbWriteTable(con, c("guest.MikeTestTable"), df)`, it creates a whole new table called `dbo.guest.MikeTestTable` rather than writing to the existing `guest.MikeTestTable`

**Comment by jcpayne** [comment] 2017-07-26 20:24
The table should not exist before you use dbWriteTable, unless you set flags to overwrite or append to it.  The RPostgreSQL manual "dbReadTable Methods" section gives an example that checks for an existing table and removes it before writing a new one.  However, DBI includes flags for overwriting or appending to the table, and the DBI documentation says:
> dbWriteTable() returns TRUE, invisibly. If the table exists, and both append and overwrite ar- guments are unset, or append = TRUE and the data frame with the new data has different column names, an error is raised; the remote table remains unchanged.

**Comment by EthanTaft** [comment] 2017-07-26 20:26
There is still an issue when using `append = TRUE`  Please see this [issue ](https://github.com/rstats-db/DBI/issues/191)

**Comment by krlmlr** [comment] 2017-12-04 20:37
Closing in favor of #24.

**Closed by krlmlr** 2017-12-04 20:37 UTC

**Comment by GaneshHegde25** [comment] 2019-05-30 17:12
I am also facing problem with dbWriteTable with oracle database. I couldn't append existing table in the same schema as well as other schema. Below workaround also didn't work.
dbWriteTable(connection, c(db_schema,table_name), value = df,  append = TRUE)
Any update on the fix?

**Comment by cf814** [comment] 2019-06-07 20:36
I've avoided this problem with dbWriteTable and dbReadTable by using dbGetQuery (for reading) and dbSendQuery (for writing) by simply specifying in the sql statement the full db.schema.table as follows: 

dbGetQuery(con, statement = "SELECT * 
                          FROM [db].[schema].[table] 
                         WHERE [date] >= '2019-05-01' and [date] < '2019-06-01';")

**Comment by aryoda** [comment] 2019-10-21 19:41
> I am also facing problem with dbWriteTable with oracle database. I couldn't append existing table in the same schema as well as other schema. Below workaround also didn't work.
> dbWriteTable(connection, c(db_schema,table_name), value = df, append = TRUE)
> Any update on the fix?

If your problem still exists please open a new issue with a minimal reproducible example (code) instead of posting this here in a closed issue. THX :-)

**Comment by timstallmann** [comment] 2020-02-24 19:23
The RStudio documentation suggests using `name = SQL("schema_name", "table_name")`, which is working for me when using RPostgres; e.g. `writeDataTable(con, SQL("schema_name", "table_name"), myDataFrame)`
