### ISSUE TITLE
Feature request: implement timeouts for queries

### ISSUE THREAD

**Issue by bborgesr** [r-dbi/DBI#123] opened 2016-07-12 02:33 UTC
I realize this is a long, long way down the road, but wanted to leave the note here anyway. It would be nice to be able to specify for how long a connection should attempt to query the database, before throwing an error... (Or how long to try to create a new connection.)

**Comment by krlmlr** [comment] 2016-08-01 11:33
Sure, we can add a `timeout` argument to the relevant functions to the specification.

**Comment by Aylr** [comment] 2018-03-06 18:30
This would be very useful rather than hanging indefinitely. Which functions would need this argument?

**Comment by krlmlr** [comment] 2019-08-23 07:48
Essentially a duplicate of #69. First we need to make sure that blocking code is interruptible and repeatable.

**Closed by krlmlr** 2019-08-23 07:48 UTC
